name: Build Flutter APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.x'
        channel: 'stable'

    - name: Generate Clean Android Workspace
      run: |
        flutter create . --platforms=android --org com.keshav.cyber --project-name keshav_online_cyber
        echo "android.useAndroidX=true" >> android/gradle.properties
        echo "android.enableJetifier=true" >> android/gradle.properties

    - name: Get Dependencies
      run: flutter pub get

    - name: Build APK Release
      run: flutter build apk --release

    - uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
        
